# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_first_name: <%= ENV['ADMIN_FIRST_NAME'] %>
  admin_last_name: <%= ENV['ADMIN_LAST_NAME'] %>
  admin_email: <%= ENV['ADMIN_EMAIL'] %>
  admin_password: <%= ENV['ADMIN_PASSWORD'] %>
  department_id: <%= ENV['DEPARTMENT_ID'] %>
  instructor_first_name: <%= ENV['INSTRUCTOR_FIRST_NAME'] %>
  instructor_last_name: <%= ENV['INSTRUCTOR_LAST_NAME'] %>
  instructor_email: <%= ENV['INSTRUCTOR_EMAIL'] %>
  instructor_password: <%= ENV['INSTRUCTOR_PASSWORD'] %>
  instructor2_first_name: <%= ENV['INSTRUCTOR2_FIRST_NAME'] %>
  instructor2_last_name: <%= ENV['INSTRUCTOR2_LAST_NAME'] %>
  instructor2_email: <%= ENV['INSTRUCTOR2_EMAIL'] %>
  instructor2_password: <%= ENV['INSTRUCTOR2_PASSWORD'] %>
  librarian_first_name: <%= ENV['LIBRARIAN_FIRST_NAME'] %>
  librarian_last_name: <%= ENV['LIBRARIAN_LAST_NAME'] %>
  librarian_email: <%= ENV['LIBRARIAN_EMAIL'] %>
  librarian_password: <%= ENV['LIBRARIAN_PASSWORD'] %>
  student_first_name: <%= ENV['STUDENT_FIRST_NAME'] %>
  student_last_name: <%= ENV['STUDENT_LAST_NAME'] %>
  student_email: <%= ENV['STUDENT_EMAIL'] %>
  student_password: <%= ENV['STUDENT_PASSWORD'] %>
  student2_first_name: <%= ENV['STUDENT2_FIRST_NAME'] %>
  student2_last_name: <%= ENV['STUDENT2_LAST_NAME'] %>
  student2_email: <%= ENV['STUDENT2_EMAIL'] %>
  student2_password: <%= ENV['STUDENT2_PASSWORD'] %>
  email_provider_username: <%= ENV['GMAIL_USERNAME'] %>
  email_provider_password: <%= ENV['GMAIL_PASSWORD'] %>
  domain_name: example.com
  secret_key_base: 5c2d20f4f56f5ba4012e70a9a2a0ad9b0fabfca15a3ffa4e6dc5b5b9df962f9350a544d35b08fefd55f5f1126b04654ac6ba778c7ae165b3234109322dfbefe9
  
test:
  domain_name: example.com 
  secret_key_base: 24359438f877f0167066777d9e57cadfd5f2473430039d1655dd02e40cab6d163f347f65c2cadf41bd1806845f9e4f48fd5335b244324782e85ed548859decd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_first_name: <%= ENV['ADMIN_FIRST_NAME'] %>
  admin_last_name: <%= ENV['ADMIN_LAST_NAME'] %>
  admin_email: <%= ENV['ADMIN_EMAIL'] %>
  admin_password: <%= ENV['ADMIN_PASSWORD'] %>
  department_id: <%= ENV['DEPARTMENT_ID'] %>
  instructor_first_name: <%= ENV['INSTRUCTOR_FIRST_NAME'] %>
  instructor_last_name: <%= ENV['INSTRUCTOR_LAST_NAME'] %>
  instructor_email: <%= ENV['INSTRUCTOR_EMAIL'] %>
  instructor_password: <%= ENV['INSTRUCTOR_PASSWORD'] %>
  instructor2_first_name: <%= ENV['INSTRUCTOR2_FIRST_NAME'] %>
  instructor2_last_name: <%= ENV['INSTRUCTOR2_LAST_NAME'] %>
  instructor2_email: <%= ENV['INSTRUCTOR2_EMAIL'] %>
  instructor2_password: <%= ENV['INSTRUCTOR2_PASSWORD'] %>
  librarian_first_name: <%= ENV['LIBRARIAN_FIRST_NAME'] %>
  librarian_last_name: <%= ENV['LIBRARIAN_LAST_NAME'] %>
  librarian_email: <%= ENV['LIBRARIAN_EMAIL'] %>
  librarian_password: <%= ENV['LIBRARIAN_PASSWORD'] %>
  student_first_name: <%= ENV['STUDENT_FIRST_NAME'] %>
  student_last_name: <%= ENV['STUDENT_LAST_NAME'] %>
  student_email: <%= ENV['STUDENT_EMAIL'] %>
  student_password: <%= ENV['STUDENT_PASSWORD'] %>
  student2_first_name: <%= ENV['STUDENT2_FIRST_NAME'] %>
  student2_last_name: <%= ENV['STUDENT2_LAST_NAME'] %>
  student2_email: <%= ENV['STUDENT2_EMAIL'] %>
  student2_password: <%= ENV['STUDENT2_PASSWORD'] %>
  email_provider_username: <%= ENV['GMAIL_USERNAME'] %>
  email_provider_password: <%= ENV['GMAIL_PASSWORD'] %>
  domain_name: <%= ENV['DOMAIN_NAME'] %> 
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
